application: fourasdemain
version: 1
runtime: go
api_version: go1

handlers:
- url: /api/.*
  script: _go_app
- url: /(.+)/
  static_files: public/\1/index.html
  upload: public/(.+)/index.html
- url: /
  static_files: public/index.html
  upload: public/index.html
- url: /
  static_dir: public
